INSERT INTO City(id, name, lat, lon) VALUES (1,'Leeds',53.801277,-1.548567);
INSERT INTO City(id, name, lat, lon) VALUES (2,'Solihull',52.412811,-1.778197);
INSERT INTO City(id, name, lat, lon) VALUES (3,'Cardiff',51.481583,-3.17909);
INSERT INTO City(id, name, lat, lon) VALUES (4,'Eastbourne',50.768036,0.290472);
INSERT INTO City(id, name, lat, lon) VALUES (5,'London',51.509865,-0.118092);
INSERT INTO City(id, name, lat, lon) VALUES (6,'Swindon',51.568535,-1.772232);
INSERT INTO City(id, name, lat, lon) VALUES (7,'Oxford',51.752022,-1.257677);
INSERT INTO City(id, name, lat, lon) VALUES (8,'Salisbury',51.068787,-1.794472);
INSERT INTO City(id, name, lat, lon) VALUES (9,'Weymouth',50.614429,-2.457621);
INSERT INTO City(id, name, lat, lon) VALUES (10,'Bournemouth',50.720806,-1.904755);
INSERT INTO City(id, name, lat, lon) VALUES (11,'Plymouth',50.376289,-4.143841);
INSERT INTO City(id, name, lat, lon) VALUES (12,'Inverness',57.477772,-4.224721);
INSERT INTO City(id, name, lat, lon) VALUES (13,'Aberdeen',57.149651,-2.099075);
INSERT INTO City(id, name, lat, lon) VALUES (14,'Ayr',55.458565,-4.629179);
INSERT INTO City(id, name, lat, lon) VALUES (15,'Belfast',54.607868,-5.926437);
INSERT INTO City(id, name, lat, lon) VALUES (16,'Londonderry',55.006763,-7.318268);
INSERT INTO City(id, name, lat, lon) VALUES (17,'Harlow',51.772938,0.10231);


INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Caroline',41,'Corporate Lawyer',153,1,'http://thecatapi.com/api/images/get?format=src&type=gif',0.76,2,'True','Atheist');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Sharon',47,'Doctor',161,2,'http://thecatapi.com/api/images/get?format=src&type=gif',0.97,0,'False','Islam');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Natalia',38,'Project Manager',144,3,'http://thecatapi.com/api/images/get?format=src&type=gif',0.47,5,'False','Christian');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Marta',55,'Finance',140,4,'http://thecatapi.com/api/images/get?format=src&type=gif',0.95,0,'False','Agnostic');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Maria',43,'CEO',175,5,'http://thecatapi.com/api/images/get?format=src&type=gif',0.88,0,'False','Christian');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Stephanie',39,'Project Manager',153,5,NULL,0.87,4,'False','Christian');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Claire',48,'GP',167,5,'http://thecatapi.com/api/images/get?format=src&type=gif',0.83,6,'False','Atheist');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Colette',39,'Doctor - Hospital',177,6,'http://thecatapi.com/api/images/get?format=src&type=gif',0.89,2,'False','Christian');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Caroline',43,'Marketing Consultant',160,7,'http://thecatapi.com/api/images/get?format=src&type=gif',0.91,1,'False','Atheist');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Kate',42,'Psychologist',160,8,'http://thecatapi.com/api/images/get?format=src&type=gif',0.97,10,'False','Buddhist');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Katie',40,'Lawyer',148,9,NULL,0.94,0,'False','Atheist');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Clare',40,'Accountant',144,10,'http://thecatapi.com/api/images/get?format=src&type=gif',0.9,8,'False','Christian');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Laura',39,'Lawyer',160,11,'http://thecatapi.com/api/images/get?format=src&type=gif',0.89,0,'False','Christian');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Katlin',39,'Barrister',153,12,'http://thecatapi.com/api/images/get?format=src&type=gif',0.87,0,'True','Jewish');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Tracy',39,'Lawyer',153,13,'http://thecatapi.com/api/images/get?format=src&type=gif',0.87,0,'False','Christian');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Angie',50,'Accountant',153,14,'http://thecatapi.com/api/images/get?format=src&type=gif',0.93,8,'True','Atheist');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Samantha',32,'Project Manager',161,15,'http://thecatapi.com/api/images/get?format=src&type=gif',0.89,0,'False','Christian');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Elizabeth',41,'Dentist',145,16,'http://thecatapi.com/api/images/get?format=src&type=gif',0.83,4,'True','Islam');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Emma',40,'Banker',150,1,'http://thecatapi.com/api/images/get?format=src&type=gif',0.73,0,'False','Christian');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Diana',44,'Consultant',153,5,'http://thecatapi.com/api/images/get?format=src&type=gif',0.5,0,'False','Atheist');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Kysha',45,'Lawyer',144,5,NULL,0.88,10,'True','Islam');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Anne',38,'Marketing Consultant',170,6,'http://thecatapi.com/api/images/get?format=src&type=gif',0.88,0,'False','Jewish');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Daniela',37,'Doctor',177,10,'http://thecatapi.com/api/images/get?format=src&type=gif',0.76,0,'False','Christian');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Katherine',39,'Lawyer',177,5,'http://thecatapi.com/api/images/get?format=src&type=gif',0.99,50,'True','Atheist');
INSERT INTO Person(display_name, age, job_title, height_in_cm, city_id, main_photo, compatibility_score, contacts_exchanged, favourite, religion) VALUES ('Susan',25,'Project Manager',166,17,'http://thecatapi.com/api/images/get?format=src&type=gif',0.88,0,'False','Christian');

